In [80]:
import numpy as np
import math

In [93]:
# 观测序列的值以及三枚硬币的初始概率
observe_Y = np.array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1])
P_a_0 = 0.5
P_b_0 = 0.5
P_c_0 = 0.5
P_a = np.array([])
P_b = np.array([])
P_c = np.array([])
E_step_matrix = np.array([])

In [94]:
P_a = np.append(P_a, P_a_0)
P_b = np.append(P_b, P_b_0)
P_c = np.append(P_c, P_c_0)

In [95]:
P_a

array([0.5])

In [96]:
for i in range(0, 10):
    # E-step
    E_step_vec = np.array([])
    for j in range(0, len(observe_Y)):
        sigma = P_a[i] * math.pow(P_b[i], observe_Y[j]) * math.pow(1 - P_b[i], 1 - observe_Y[j]) + (1 - P_a[i]) * math.pow(P_c[i], observe_Y[j]) * math.pow(1 - P_c[i], 1 - observe_Y[j])
        p_from_b = P_a[i] * math.pow(P_b[i], observe_Y[j]) * math.pow(1 - P_b[i], 1 - observe_Y[j]) / sigma
        E_step_vec = np.append(E_step_vec, p_from_b)
    E_step_matrix = np.append(E_step_matrix, E_step_vec)
    
    # M-step
    sum1 = 0
    sum2 = 0
    for k in E_step_vec:
        sum1 += k
    for k in 1 - E_step_vec:
        sum2 += k
    p_a_i_plus = sum1 / len(observe_Y)
    p_b_i_plus = np.dot(E_step_vec.T, observe_Y) / sum1
    p_c_i_plus = np.dot(1 - E_step_vec.T, observe_Y) / sum2
    
    P_a = np.append(P_a, p_a_i_plus)
    P_b = np.append(P_b, p_b_i_plus)
    P_c = np.append(P_c, p_c_i_plus)
    
    print(i + 1)
    print(E_step_vec)
    print(P_a)
    print('P(A):' + str(p_a_i_plus) + '  P(B):' + str(p_b_i_plus) + '  P(C):' + str(p_c_i_plus))

1
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
2
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
3
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
4
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
5
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5 0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
6
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
7
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
8
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
9
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
P(A):0.5  P(B):0.6  P(C):0.6
10
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
P(A):0.5  P(B):0.6